name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    strategy:
          matrix:
            projects:
              - HomeApplianceXML
              - dashboard-ew2020
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: ${{ matrix.projects }}
      run: mvn package
    - name: Compressing artifacts
      run: |
        mkdir -p artifacts
        mv ${{ matrix.projects }}/target/install/linux_arm artifacts/${{ matrix.projects }}
    - name: Archive results
      uses: actions/upload-artifact@v1
      with:
        name: totalcross-embedded-samples
        path: artifacts
